apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-init-script
  namespace: database
spec:
  version: "8.0-v1"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  databaseSecret:
    secretName: mysql-init-auth
  init:
    scriptSource:
      configMap:
        name: mysql-init-configmap
  monitor:
    agent: prometheus.io/builtin