apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: administrateur
subjects:
- kind: User
  name: administrateur-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: administrateur
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysops
subjects:
- kind: User
  name: sysops-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sysops
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev
subjects:
- kind: User
  name: dev-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client
subjects:
- kind: User
  name: client-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: client
  apiGroup: rbac.authorization.k8s.io